filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/zeek/*.log
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  fields:
    event.dataset: "zeek"
  tags: ["zeek"]

- type: log
  enabled: true
  paths:
    - /var/log/suricata/eve.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  fields:
    event.dataset: "suricata"
  tags: ["suricata"]

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["https://opensearch-node1:9200"]
  username: "admin"
  password: "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
  ssl.verification_mode: none
  index: "thunderx-%{[event.dataset]}-%{+yyyy.MM.dd}"

setup.template.name: "thunderx"
setup.template.pattern: "thunderx-*"
